services:
  - type: web
    name: amazon-price-checker
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install --with-deps chromium
    startCommand: gunicorn app:app
