services:
  - type: web
    name: amazon-price-checker
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: gunicorn app:app
    runtime: python
    region: oregon
    branch: main
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
