services:
  - type: web
    name: amazon-price-checker
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m playwright install chromium && gunicorn app:app
